### ISSUE TITLE
Randomly Capatalize A Character in a String

### ISSUE THREAD

**Issue by carlosrrod** [carlosrrod/pypassgen#1]
## The problem
I want a generated password to include characters that are capitalized randomly. For example, given this string: `my_string = 'cheesecake'` I want an output string to be something like this `new_string = 'chEeseCakE'`

> Of note: This password generated script injects numbers and special characters into the string, however these shouldn't be effected by capitalization 

## To get started
You'll find that the code that generates the string is located in the `passgen.py` file and the function responsible is `def build_pass()` 

```python
random_word = get_word()
    # 2. Setup special characters and numbers
    special_chars = ['!', '@', '#', '$', '%', '&', '*', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9']
    # 3. Setup empty string as a placeholder for new password
    new_pass = ''
    # 4. Loop through every character in random_word
    for letter in random_word:
        pass_len = len(new_pass)
        special_len = len(special_chars)
        # Create random numbers
        rand_num1 = random.randint(0, special_len)
        rand_num2 = random.randint(0, pass_len)
        # 5. Inject special characters or numbers into the new password
        new_pass += letter
        new_pass += special_chars[rand_num1-1]

        # 6. Capatalize a random letter
        new_pass[rand_num2].upper() # << NOT WORKING PROPERLY
```

**Comment by jounilammi** [comment]
I did a pull request that fixes this issue. Let me know what you think, and I'll update my PR accordingly.

**Comment by carlosrrod** [comment]
Works great! Thank you 🙏
