### ISSUE TITLE
Storing Data into JSON

### ISSUE THREAD

**Issue by carlosrrod** [carlosrrod/pypassgen#7]
This application needs a way of storing generated passwords into a local JSON file *`password_data.json`*.  Passwords are generated by the **`Passwords`** class and is triggered by the *`pass_gen_btn`* in the **`MainWindow`** class. The JSON structure should be as follows:

```json
{
  "generated_passwords": [
      {"password" : "2anc&h32iDh29&YH38",
       "date": "04/20/2020"
      },
      {"password" : "39Jnba^^^@3djNN",
       "date": "04/21/2020"
      }
  ]
}
```

If you have a better suggestion for what the JSON structure should be, please comment on it. I am open to suggestions.

**Comment by drholera** [comment]
I'd like to work on it.

**Comment by drholera** [comment]
Hello @carlosrrod 
Please review the PR #8.

**Comment by carlosrrod** [comment]
@drholera Your PR was merged. Great job! Tested and functioning as intended.
